//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Our Projects </summary>
	[PublishedModel("ourProjects")]
	public partial class OurProjects : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "ourProjects";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<OurProjects, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public OurProjects(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Email Ticket - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("emailTicketText")]
		public virtual string EmailTicketText => this.Value<string>(_publishedValueFallback, "emailTicketText");

		///<summary>
		/// Email Ticket - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("emailTicketTitle")]
		public virtual string EmailTicketTitle => this.Value<string>(_publishedValueFallback, "emailTicketTitle");

		///<summary>
		/// Hero - OnatrixLogo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroOnatrixLogo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops HeroOnatrixLogo => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "heroOnatrixLogo");

		///<summary>
		/// Our Projects - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourProjectsHeadline")]
		public virtual string OurProjectsHeadline => this.Value<string>(_publishedValueFallback, "ourProjectsHeadline");

		///<summary>
		/// Our Projects - Projects
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourProjectsProjects")]
		public virtual string OurProjectsProjects => this.Value<string>(_publishedValueFallback, "ourProjectsProjects");

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");

		///<summary>
		/// ProjectDate1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDate1")]
		public virtual string ProjectDate1 => this.Value<string>(_publishedValueFallback, "projectDate1");

		///<summary>
		/// ProjectDate2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDate2")]
		public virtual string ProjectDate2 => this.Value<string>(_publishedValueFallback, "projectDate2");

		///<summary>
		/// ProjectDate3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDate3")]
		public virtual string ProjectDate3 => this.Value<string>(_publishedValueFallback, "projectDate3");

		///<summary>
		/// ProjectDate4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDate4")]
		public virtual string ProjectDate4 => this.Value<string>(_publishedValueFallback, "projectDate4");

		///<summary>
		/// ProjectHeadline1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectHeadline1")]
		public virtual string ProjectHeadline1 => this.Value<string>(_publishedValueFallback, "projectHeadline1");

		///<summary>
		/// ProjectHeadline2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectHeadline2")]
		public virtual string ProjectHeadline2 => this.Value<string>(_publishedValueFallback, "projectHeadline2");

		///<summary>
		/// ProjectHeadline3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectHeadline3")]
		public virtual string ProjectHeadline3 => this.Value<string>(_publishedValueFallback, "projectHeadline3");

		///<summary>
		/// ProjectHeadline4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectHeadline4")]
		public virtual string ProjectHeadline4 => this.Value<string>(_publishedValueFallback, "projectHeadline4");

		///<summary>
		/// ProjectImage1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectImage1")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectImage1 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectImage1");

		///<summary>
		/// ProjectImage2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectImage2")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectImage2 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectImage2");

		///<summary>
		/// ProjectImage3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectImage3")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectImage3 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectImage3");

		///<summary>
		/// ProjectImage4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectImage4")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectImage4 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectImage4");

		///<summary>
		/// Project Tags - Tag - App
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsTagApp")]
		public virtual string ProjectTagsTagApp => this.Value<string>(_publishedValueFallback, "projectTagsTagApp");

		///<summary>
		/// Project Tags - Tag - Buisnes plans
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsTagBuisnesPlans")]
		public virtual string ProjectTagsTagBuisnesPlans => this.Value<string>(_publishedValueFallback, "projectTagsTagBuisnesPlans");

		///<summary>
		/// Project Tags - Tag - Business
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsTagBusiness")]
		public virtual string ProjectTagsTagBusiness => this.Value<string>(_publishedValueFallback, "projectTagsTagBusiness");

		///<summary>
		/// Project Tags - Tag - Finance
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsTagFinance")]
		public virtual string ProjectTagsTagFinance => this.Value<string>(_publishedValueFallback, "projectTagsTagFinance");

		///<summary>
		/// Project Tags - Tag - Insights
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsTagInsights")]
		public virtual string ProjectTagsTagInsights => this.Value<string>(_publishedValueFallback, "projectTagsTagInsights");

		///<summary>
		/// Project Tags - Tag - Pricing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsTagPricing")]
		public virtual string ProjectTagsTagPricing => this.Value<string>(_publishedValueFallback, "projectTagsTagPricing");

		///<summary>
		/// Project Tags - Tag - Project
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsTagProject")]
		public virtual string ProjectTagsTagProject => this.Value<string>(_publishedValueFallback, "projectTagsTagProject");

		///<summary>
		/// Project Tags - Tag - Report
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsTagReport")]
		public virtual string ProjectTagsTagReport => this.Value<string>(_publishedValueFallback, "projectTagsTagReport");

		///<summary>
		/// Project Tags - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsTitle")]
		public virtual string ProjectTagsTitle => this.Value<string>(_publishedValueFallback, "projectTagsTitle");

		///<summary>
		/// ProjectText1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectText1")]
		public virtual string ProjectText1 => this.Value<string>(_publishedValueFallback, "projectText1");

		///<summary>
		/// ProjectText2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectText2")]
		public virtual string ProjectText2 => this.Value<string>(_publishedValueFallback, "projectText2");

		///<summary>
		/// ProjectText3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectText3")]
		public virtual string ProjectText3 => this.Value<string>(_publishedValueFallback, "projectText3");

		///<summary>
		/// ProjectText4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectText4")]
		public virtual string ProjectText4 => this.Value<string>(_publishedValueFallback, "projectText4");

		///<summary>
		/// Your Project - Email - EmailAddress
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectEmailEmailAddress")]
		public virtual string YourProjectEmailEmailAddress => this.Value<string>(_publishedValueFallback, "yourProjectEmailEmailAddress");

		///<summary>
		/// Your Project - Email - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectEmailHeadline")]
		public virtual string YourProjectEmailHeadline => this.Value<string>(_publishedValueFallback, "yourProjectEmailHeadline");

		///<summary>
		/// Your Project - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectHeadline")]
		public virtual string YourProjectHeadline => this.Value<string>(_publishedValueFallback, "yourProjectHeadline");

		///<summary>
		/// Your Project - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops YourProjectImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "yourProjectImage");

		///<summary>
		/// Your Project - Location - Address
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectLocationAddress")]
		public virtual string YourProjectLocationAddress => this.Value<string>(_publishedValueFallback, "yourProjectLocationAddress");

		///<summary>
		/// Your Project - Location - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectLocationHeadline")]
		public virtual string YourProjectLocationHeadline => this.Value<string>(_publishedValueFallback, "yourProjectLocationHeadline");

		///<summary>
		/// Your Project - PhoneNumber - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectPhoneNumberHeadline")]
		public virtual string YourProjectPhoneNumberHeadline => this.Value<string>(_publishedValueFallback, "yourProjectPhoneNumberHeadline");

		///<summary>
		/// Your Project - PhoneNumber - Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectPhoneNumberNumber")]
		public virtual string YourProjectPhoneNumberNumber => this.Value<string>(_publishedValueFallback, "yourProjectPhoneNumberNumber");
	}
}
