//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Risk Management Page</summary>
	[PublishedModel("riskManagementPage")]
	public partial class RiskManagementPage : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "riskManagementPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<RiskManagementPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public RiskManagementPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// About us management - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsManagementHeadline")]
		public virtual string AboutUsManagementHeadline => this.Value<string>(_publishedValueFallback, "aboutUsManagementHeadline");

		///<summary>
		/// About us management - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsManagementImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutUsManagementImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutUsManagementImage");

		///<summary>
		/// About us management - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsManagementText")]
		public virtual string AboutUsManagementText => this.Value<string>(_publishedValueFallback, "aboutUsManagementText");

		///<summary>
		/// financial confidence - headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialConfidenceHeadline")]
		public virtual string FinancialConfidenceHeadline => this.Value<string>(_publishedValueFallback, "financialConfidenceHeadline");

		///<summary>
		/// financial confidence - text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialConfidenceText1")]
		public virtual string FinancialConfidenceText1 => this.Value<string>(_publishedValueFallback, "financialConfidenceText1");

		///<summary>
		/// financial confidence - text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialConfidenceText2")]
		public virtual string FinancialConfidenceText2 => this.Value<string>(_publishedValueFallback, "financialConfidenceText2");

		///<summary>
		/// financial confidence - text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialConfidenceText3")]
		public virtual string FinancialConfidenceText3 => this.Value<string>(_publishedValueFallback, "financialConfidenceText3");

		///<summary>
		/// financial confidence - text4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialConfidenceText4")]
		public virtual string FinancialConfidenceText4 => this.Value<string>(_publishedValueFallback, "financialConfidenceText4");

		///<summary>
		/// financial confidence - text5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialConfidenceText5")]
		public virtual string FinancialConfidenceText5 => this.Value<string>(_publishedValueFallback, "financialConfidenceText5");

		///<summary>
		/// financial plan - headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialPlanHeadline")]
		public virtual string FinancialPlanHeadline => this.Value<string>(_publishedValueFallback, "financialPlanHeadline");

		///<summary>
		/// financial plan - image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialPlanImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FinancialPlanImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "financialPlanImage");

		///<summary>
		/// financial plan - text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialPlanText1")]
		public virtual string FinancialPlanText1 => this.Value<string>(_publishedValueFallback, "financialPlanText1");

		///<summary>
		/// financial plan - text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialPlanText2")]
		public virtual string FinancialPlanText2 => this.Value<string>(_publishedValueFallback, "financialPlanText2");

		///<summary>
		/// financial plan - text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialPlanText3")]
		public virtual string FinancialPlanText3 => this.Value<string>(_publishedValueFallback, "financialPlanText3");

		///<summary>
		/// financial plan - text4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialPlanText4")]
		public virtual string FinancialPlanText4 => this.Value<string>(_publishedValueFallback, "financialPlanText4");

		///<summary>
		/// financial plan - text5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialPlanText5")]
		public virtual string FinancialPlanText5 => this.Value<string>(_publishedValueFallback, "financialPlanText5");

		///<summary>
		/// financial plan - text6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialPlanText6")]
		public virtual string FinancialPlanText6 => this.Value<string>(_publishedValueFallback, "financialPlanText6");

		///<summary>
		/// financial plan - text7
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialPlanText7")]
		public virtual string FinancialPlanText7 => this.Value<string>(_publishedValueFallback, "financialPlanText7");

		///<summary>
		/// financial plan - text8
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("financialPlanText8")]
		public virtual string FinancialPlanText8 => this.Value<string>(_publishedValueFallback, "financialPlanText8");

		///<summary>
		/// Hero - OnatrixLogo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroOnatrixLogo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops HeroOnatrixLogo => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "heroOnatrixLogo");

		///<summary>
		/// Key point - headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("keyPointHeadline")]
		public virtual string KeyPointHeadline => this.Value<string>(_publishedValueFallback, "keyPointHeadline");

		///<summary>
		/// key point - text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("keyPointText1")]
		public virtual string KeyPointText1 => this.Value<string>(_publishedValueFallback, "keyPointText1");

		///<summary>
		/// key point - text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("keyPointText2")]
		public virtual string KeyPointText2 => this.Value<string>(_publishedValueFallback, "keyPointText2");

		///<summary>
		/// key point - text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("keyPointText3")]
		public virtual string KeyPointText3 => this.Value<string>(_publishedValueFallback, "keyPointText3");

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");

		///<summary>
		/// Risk Management - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RiskManagementImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "riskManagementImage");

		///<summary>
		/// Risk management - Navgiation1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementNavgiation1")]
		public virtual string RiskManagementNavgiation1 => this.Value<string>(_publishedValueFallback, "riskManagementNavgiation1");

		///<summary>
		/// Risk management - Navgiation2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementNavgiation2")]
		public virtual string RiskManagementNavgiation2 => this.Value<string>(_publishedValueFallback, "riskManagementNavgiation2");

		///<summary>
		/// Risk management - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementTitle")]
		public virtual string RiskManagementTitle => this.Value<string>(_publishedValueFallback, "riskManagementTitle");

		///<summary>
		/// Support ticket - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("supportTicketHeadline")]
		public virtual string SupportTicketHeadline => this.Value<string>(_publishedValueFallback, "supportTicketHeadline");

		///<summary>
		/// Support ticket - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("supportTicketText")]
		public virtual string SupportTicketText => this.Value<string>(_publishedValueFallback, "supportTicketText");

		///<summary>
		/// Your Project - Email - EmailAddress
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectEmailEmailAddress")]
		public virtual string YourProjectEmailEmailAddress => this.Value<string>(_publishedValueFallback, "yourProjectEmailEmailAddress");

		///<summary>
		/// Your Project - Email - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectEmailHeadline")]
		public virtual string YourProjectEmailHeadline => this.Value<string>(_publishedValueFallback, "yourProjectEmailHeadline");

		///<summary>
		/// Your Project - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectHeadline")]
		public virtual string YourProjectHeadline => this.Value<string>(_publishedValueFallback, "yourProjectHeadline");

		///<summary>
		/// Your Project - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops YourProjectImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "yourProjectImage");

		///<summary>
		/// Your Project - Location - Address
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectLocationAddress")]
		public virtual string YourProjectLocationAddress => this.Value<string>(_publishedValueFallback, "yourProjectLocationAddress");

		///<summary>
		/// Your Project - Location - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectLocationHeadline")]
		public virtual string YourProjectLocationHeadline => this.Value<string>(_publishedValueFallback, "yourProjectLocationHeadline");

		///<summary>
		/// Your Project - PhoneNumber - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectPhoneNumberHeadline")]
		public virtual string YourProjectPhoneNumberHeadline => this.Value<string>(_publishedValueFallback, "yourProjectPhoneNumberHeadline");

		///<summary>
		/// Your Project - PhoneNumber - Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yourProjectPhoneNumberNumber")]
		public virtual string YourProjectPhoneNumberNumber => this.Value<string>(_publishedValueFallback, "yourProjectPhoneNumberNumber");
	}
}
